### ISSUE TITLE
Suggestion: date

### ISSUE THREAD

**Issue by lukascamargo** [taylanken/mongoose-version-history#3]
Hi! 

I'm using the mongoose-version-history and I think it is amazing. But I think it could have an date field to show the date that the version was created. At least in my projects it would be VERY useful.

What you think about it?

**Comment by taylanken** [comment]
Hi,

thanks for the great suggestion. Will add a date field.

**Comment by taylanken** [comment]
@lukasfialho Added date tracking features. Please update to version **0.3.0** to make use of them. Please read the updated README.md to learn how to enable date tracking. Especially pay attention to the new options **trackDate**, **addDateToDocument** and **versionDateKey**.
